#!/bin/bash

# reference 1
# https://daily-dev-tips.com/posts/removing-a-env-file-from-git-history/

# reference 2
https://stackoverflow.com/questions/6403601/purging-file-from-git-repo-failed-unable-to-create-new-backup

if [ -z $1 ]; then
echo "usage: $0 <file-to-be-removed> [path]"
exit
fi

if [ ! -z $2 ];then
cd $2
fi

git filter-branch --index-filter "git rm -rf --cached --ignore-unmatch $1" HEAD
git update-ref -d refs/original/refs/heads/master
git push -f
