#!/bin/bash
file=backup-server-`date --iso-8601`
cd ~
mysqldump --add-drop-table -u root -h localhost -p$(cat .mysql_pass) --all-databases > ${file}.sql
tar cjf ${file}.tbz html/ ${file}.sql
find ~ -iname 'backup-server-*' -ctime +7 -delete 2> /dev/null
