#!/bin/bash

read -p "Are you sure you want to delete all images? [y/N] " answer
if [ "$answer" != "y" ]; then
  echo "$0 - Operation canceled"
  exit
fi

# remove all images
docker rmi -f $(docker images -q)
