#!/bin/bash

read -p "Are you sure you want to delete all containers? [y/N] " answer
if [ "$answer" != "y" ]; then
  echo "$0 - Operation canceled"
  exit
fi

# remove all containers
docker rm -f $(docker ps -a -q)
