#!/usr/bin/env python3
#https://stackoverflow.com/a/39596292

import secrets
import string

alphabet = string.ascii_letters + string.digits
password = ''.join(secrets.choice(alphabet) for i in range(20)) 
print(password)