#!/bin/bash

for f in `ls laradock-scripts/laradock*`; do
  file=`basename $f`
  if [ ! -e $file ]; then
    echo "Created link to -> $f"
    ln -s $f .
  else
    echo "File $file already exists"
  fi
done

