#!/bin/bash

file=`basename $0`

# help message
if [ "$1" == "--help" ]; then
echo "$file - enter in a container to exec commands"
exit
fi

if [ ! -d laradock ]; then
echo "$file - no laradock found"
exit
fi

dir=$(basename `pwd`)
cd laradock
docker exec --user=laradock -it ${dir}_workspace_1 bash
