#!/bin/bash

file=`basename $0`

# help message
if [ "$1" == "--help" ]; then
echo "$file - up a laradock project"
exit
fi

if [ ! -d laradock ]; then
echo "$file - no laradock found"
exit
fi

cd laradock
docker-compose up -d nginx mysql adminer
