#!/bin/bash

# use with super user warning
if [[ $USER != "root" ]]; then
  echo "delsite: use with super user"
  exit
fi

# if empty return usage message and exit
if [ -z $1 ]; then

  echo "Usage: delsite example.com"
  exit
fi

DOMAIN=$1
USER=`echo $1 | tr -d "."`

# disable site in apache
cd /etc/apache2/sites-enabled
a2dissite $1\.conf

read -p "Remove user and all files? (Y/n)" REMOVE

REMOVE=`echo "$REMOVE" | tr [:upper:] [:lower:]`

# ask if should remove the user
if [[ $REMOVE != "n" ]]; then
  echo "Removing user..."
  cd /home
  deluser $USER --backup --backup-to /home --remove-home
fi
